/**
 * @description
 * @author Mark Brennand
 */
@IsTest
public with sharing class TriggerTest {

    @IsTest
    private static void testName() {
        /*
        Assert.areEqual('AsynchronousJobException', TriggerAPI.getObjectKey(AsynchronousJobException__c.SObjectType.getDescribe().name));
        Assert.areEqual('Asynchronous_Job_Exception', TriggerAPI.getObjectKey('forcefw__Asynchronous_Job_Exception__c'));
         */
    }
}